---
- hosts: localhost
  connection: local

  tasks: 
  - name: start an instance with a public IP address
    amazon.aws.ec2_instance:
      name: "public-compute-instance"
      key_name: "docker-demo-key"
      instance_type: t2.micro
      security_group: sg-0753135f7c761c652
      region: us-east-1
      aws_access_key: "{{ec2_access_key}}"  # From vault as defined
      aws_secret_key: "{{ec2_secret_key}}"  # From vault as defined      
      network:
        assign_public_ip: true
      image_id: ami-0866a3c8686eaeeba
  
    
